name       : perl-image-exiftool
version    : '11.01'
release    : 9
source     :
    - https://cpan.metacpan.org/authors/id/E/EX/EXIFTOOL/Image-ExifTool-11.01.tar.gz : 705fbf4a42d772c548afff4c64b3db3e95eb347e5b48acd66dd7d7712c19bc9c
license    : Artistic-1.0-Perl
component  : multimedia.library
summary    : Reader and rewriter of EXIF informations that supports raw files
description: |
    Reader and rewriter of EXIF informations that supports raw files
builddeps  :
    - perl-archive-zip
    - perl-posix-strptime
rundeps    :
    - perl-archive-zip
    - perl-posix-strptime
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
