name       : perl-image-exiftool
version    : '10.80'
release    : 8
source     :
    - https://cpan.metacpan.org/authors/id/E/EX/EXIFTOOL/Image-ExifTool-10.80.tar.gz : bcf896600776d8ef39a867081b48426837ed5ee8ca19b53dd9d86a3179c93c93
license    : Artistic-1.0-Perl
component  : multimedia.library
summary    : Reader and rewriter of EXIF informations that supports raw files
description: |
    Reader and rewriter of EXIF informations that supports raw files
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
