name       : perl-image-exiftool
version    : '12.50'
release    : 21
source     :
    - https://cpan.metacpan.org/authors/id/E/EX/EXIFTOOL/Image-ExifTool-12.50.tar.gz : bce841fc5c10302f0f3ef7678c3bf146953a8c065c0ba18c41f734007e2ec0a8
homepage   : https://exiftool.org/
license    : Artistic-1.0-Perl
component  : multimedia.library
summary    : Reader and rewriter of EXIF informations that supports raw files
description: |
    ExifTool is a customizable set of Perl modules plus a full-featured command-line application for reading and writing meta information in a wide variety of files, including the maker note information of many digital cameras by various manufacturers such as Canon, Casio, DJI, FLIR, FujiFilm, GE, GoPro, HP, JVC/Victor, Kodak, Leaf, Minolta/Konica-Minolta, Nikon, Nintendo, Olympus/Epson, Panasonic/Leica, Pentax/Asahi, Phase One, Reconyx, Ricoh, Samsung, Sanyo, Sigma/Foveon and Sony.
builddeps  :
    - perl-archive-zip
    - perl-posix-strptime
rundeps    :
    - perl-archive-zip
    - perl-posix-strptime
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
