name       : perl-image-exiftool
version    : '11.30'
release    : 13
source     :
    - https://cpan.metacpan.org/authors/id/E/EX/EXIFTOOL/Image-ExifTool-11.30.tar.gz : 3a53733a1532bede4ce7eee763e5ab2bb87149e75e869e11a64d0e159858726e
license    : Artistic-1.0-Perl
component  : multimedia.library
summary    : Reader and rewriter of EXIF informations that supports raw files
description: |
    Reader and rewriter of EXIF informations that supports raw files
builddeps  :
    - perl-archive-zip
    - perl-posix-strptime
rundeps    :
    - perl-archive-zip
    - perl-posix-strptime
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
