name       : perl-image-exiftool
version    : 10.00
release    : 3
source     :
    - http://www.cpan.org/authors/id/E/EX/EXIFTOOL/Image-ExifTool-10.00.tar.gz : 7b573331eba3921b56339018e95dd5e6f5a1e4634e4fc7bad91e5778da3571f4
license    : GPL-2.0+
summary    : Reader and rewriter of EXIF informations that supports raw files
component  : multimedia.library
description: |
    Reader and rewriter of EXIF informations that supports raw files
patterns   :
    - /usr/share/man/man3/*
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
