name       : perl-image-exiftool
version    : '10.50'
release    : 5
source     :
    - http://www.cpan.org/authors/id/E/EX/EXIFTOOL/Image-ExifTool-10.50.tar.gz : 339dd8f771f673fd6c448f4a4b36cf50fe8e3bf884da95aef6cec1d182c0885b
license    : GPL-2.0+
summary    : Reader and rewriter of EXIF informations that supports raw files
component  : multimedia.library
description: |
    Reader and rewriter of EXIF informations that supports raw files
patterns   :
    - /usr/share/man/man3/*
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
