name       : perl-image-exiftool
version    : '10.40'
release    : 4
source     :
    - http://www.cpan.org/authors/id/E/EX/EXIFTOOL/Image-ExifTool-10.40.tar.gz : 9e3619e2f9c838b37f67ab55fd541b5472b328d5f464468442367292666a05dc
license    : GPL-2.0+
summary    : Reader and rewriter of EXIF informations that supports raw files
component  : multimedia.library
description: |
    Reader and rewriter of EXIF informations that supports raw files
patterns   :
    - /usr/share/man/man3/*
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
